apiVersion: v1
kind: Service
metadata:
  name: platform-app
  namespace: app
  labels:
    app: platform-app
spec:
  selector:
    app: platform-app
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
